const mongoose = require('mongoose');
const UserSchema = new mongoose.Schema({
    username: { type: String, required: true, unique: true },
    email: { type: String, required: true, unique: true },
    password: { type: String, required: true },
    profilePic: { type: String, default: "" },
    profilePicId: { type: String, default: "" }, 
    role: { type: String, default: "artist" },
    isVerified: { type: Boolean, default: false },
    isVerificationPending: { type: Boolean, default: false },
    coins: { type: Number, default: 0 },
    likes: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Wallpaper' }], 
    savedWallpapers: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Wallpaper' }],
    interests: { type: Map, of: Number, default: {} },
    lastDailyRewardAt: { type: Date, default: null },
    unlockedWallpapers: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Wallpaper' }],
    adsSeenToday: { type: Number, default: 0 }, 
    lastAdDate: { type: String, default: "" },    
    wallpaperCount: { type: Number, default: 0 }, 
    instagram: { type: String, default: "" },
    facebook: { type: String, default: "" },
    twitter: { type: String, default: "" }, 
    tiktok: { type: String, default: "" }, 
    threads: { type: String, default: "" },  
    web: { type: String, default: "" },
    bio: { type: String, default: "", maxLength: 60 },
    pushToken: { type: String, default: "" },
    lastNotificationSentAt: { type: Date, default: null },
    createdAt: { type: Date, default: Date.now },
    lastActiveAt: { type: Date, default: Date.now },
    lastDownloadAt: {type: Date, default: null },
    followers: [{ type: mongoose.Schema.Types.ObjectId, ref: 'User' }],
    following: [{ type: mongoose.Schema.Types.ObjectId, ref: 'User' }],
    birthday: { type: Date, default: null },
    gender: { type: String, enum: ['masculino', 'femenino', 'personalizado', 'Masculino', 'Femenino', 'Personalizado', ''], default: '' },
    country: { type: String, default: "" },
    isActive: { type: Boolean, default: true  },
    deactivatedAt: { type: Date, default: null },
    isFeedDirty: { type: Boolean, default: true},
    
});
module.exports = mongoose.model('User', UserSchema);